version: "3"
services:
  server:
    build:
      context: ./packages/milana-server
    image: milana-server
    ports:
      - "8080:8080"
    networks:
      - milana-network
    volumes:
      - server-data:/usr/src/app/data

  client:
    build:
      context: ./packages/milana-web-client
    image: milana-client
    ports:
      - "9000:9000"
    networks:
      - milana-network
    volumes:
      - client-data:/usr/src/app/data
    depends_on:
      - server

networks:
  milana-network:
    driver: bridge

volumes:
  server-data:
  client-data:
